### ISSUE TITLE
sync-issues with react-native after upgrade to @powersync/react-native@^1.25.0 and @powersync/op-sqlite@^0.7.10

### ISSUE THREAD

**Issue by sboo** [powersync-ja/powersync-js#734]
After updating to @powersync/react-native@1.25.0 (still happened with 1.25.1) and @powersync/op-sqlite@0.7.10 (as well with 0.7.11) syncing with PowerBase causes delays and errors.

Please advice what kind of information I can provide to debug this. Here's the log from the debugger:

```
Saved batch of data for  bucket: pet_data["a04879ba-2ebb-4fa2-a8be-2399ab502f65"], operations: 1
 DEBUG  Validated checksums checkpoint 1270
 DEBUG  Could not apply checkpoint 1270 due to local data. We will retry applying the checkpoint after that upload is completed.
[React] [Error: Closed. Original cause [Error: Stream end encountered].]
 ERROR  [Error: Closed. Original cause [Error: Stream end encountered].] 

Code: bundle.cjs
(/{path-to-project}/node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.cjs:22:40128)

...ror('"value" argument is out of bounds');if(u+e>l.length)throw new RangeError("Index out of range")}function ...
                                                                                                                  ^
(error truncated)
Call Stack
  n.prototype.close (node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.cjs:22:40129)
  l.prototype.close (node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.cjs:22:34545)
  call (<native>)
  n.prototype.close (node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.cjs:22:101731)
  t.handleClosed (node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.cjs:22:100852)
  call (<native>)
  invoke (node_modules/react-native/src/private/webapis/dom/events/EventTarget.js:379:22)
  dispatch (node_modules/react-native/src/private/webapis/dom/events/EventTarget.js:293:11)
  dispatchEvent (node_modules/react-native/src/private/webapis/dom/events/EventTarget.js:207:13)
  _eventEmitter.addListener$argument_1 (node_modules/react-native/Libraries/WebSocket/WebSocket.js:263:27)
  apply (<native>)
  emit (node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:130:36)
  apply (<native>)
  <anonymous> (node_modules/@babel/runtime/helpers/superPropGet.js:6:19)
  RCTDeviceEventEmitterImpl#emit (node_modules/react-native/Libraries/EventEmitter/RCTDeviceEventEmitter.js:33:5)
```

**Comment by stevensJourney** [comment]
Thanks for sharing.

Could you give a few more details in order for us to eliminate some variables:
- Which SDK version did you upgrade from? 
- Are the issues completely resolved if you revert the upgrade?
- Are you using the Rust or JS sync client?
- Are you using any other potentially advanced features, such as raw tables?

**Comment by sboo** [comment]
**Which SDK version did you upgrade from?**
"@powersync/op-sqlite": "0.7.8",
 "@powersync/react-native": "1.24.2",

**Are the issues completely resolved if you revert the upgrade?**
Yes, I just reverted and everything works as expected again.

**Are you using the Rust or JS sync client?**
It's a react-native app, so JS

**Are you using any other potentially advanced features, such as raw tables?** 
I'm also using attachments, set up just like in the demo app.
I'm also using Kysely, and to ensure this wasn't a cause, had removed everything Kysely related, but that didn't make a difference.

**Comment by sboo** [comment]
Correction: I get the same out of bounds error in the console now as well after turning back, however, I don't get the error anymore that it can't apply a checkpoint.

Still get this:
```
ERROR  [Error: Closed. Original cause [Error: Stream end encountered].] 

Code: bundle.mjs
(/{path-to-project}/node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.mjs:22:40128)

...ror('"value" argument is out of bounds');if(u+e>l.length)throw new RangeError("Index out of range")}function ...
                                                                                                                  ^
(error truncated)
Call Stack
  n.prototype.close (node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.mjs:22:40129)
  l.prototype.close (node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.mjs:22:34545)
  call (<native>)
  n.prototype.close (node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.mjs:22:101731)
  t.handleClosed (node_modules/@powersync/react-native/node_modules/@powersync/common/dist/bundle.mjs:22:100852)
  call (<native>)
  invoke (node_modules/react-native/src/private/webapis/dom/events/EventTarget.js:379:22)
  dispatch (node_modules/react-native/src/private/webapis/dom/events/EventTarget.js:293:11)
  dispatchEvent (node_modules/react-native/src/private/webapis/dom/events/EventTarget.js:207:13)
  _eventEmitter.addListener$argument_1 (node_modules/react-native/Libraries/WebSocket/WebSocket.js:263:27)
  apply (<native>)
  emit (node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:130:36)
  apply (<native>)
  <anonymous> (node_modules/@babel/runtime/helpers/superPropGet.js:6:19)
  RCTDeviceEventEmitterImpl#emit (node_modules/react-native/Libraries/EventEmitter/RCTDeviceEventEmitter.js:33:5)
```

but not this anymore:
` DEBUG  Could not apply checkpoint 1270 due to local data. We will retry applying the checkpoint after that upload is completed.`

With the updated packages, changes seem to have been applied still somehow, but the the useQuery - hook didn't fire anymore.

Can you point me in the right direction on how to debug the out-of-bounds error?

**Comment by stevensJourney** [comment]
That's interesting. I can't say we've seen this error before, so we'd need to try and reproduce it on our end.

As a test, could you try connecting with our Rust client, to see if that makes any difference? An example for doing this is [here](https://github.com/powersync-ja/powersync-js/blob/949a7d8256438a013be28953bc21659f88bb3bd0/demos/react-native-supabase-todolist/library/powersync/system.ts#L71).

Are you using a self-hosted or cloud PowerSync service? Are you seeing any potentially relevant Service logs/errors when this message is shown on the client?

**Comment by sboo** [comment]
Apologies for this mess of a report, however, I've narrowed it down now I believe.

I'm using the cloud service. This is on an iOS26 simulator with a dev-client.

In an edit-screen I'm updating a value (weight) in a record:

```
await db
        .updateTable('weight')
        .set({
          weight: data.weight,
          notes: data.notes || null,
        })
        .where('id', '=', entryId)
        .execute();
```

and then navigate back to the list of items.

```
const getWeightEntries = (
    petId: string,
  ) => {
    let query = db
      .selectFrom('weight')
      .where('weight.pet_id', '=', petId)
      .selectAll('weight')
      .orderBy('weight.created_at', 'desc');

    return query;
};

const query = getWeightEntriesQuery(petId);
const { data, isLoading, isFetching } = useQuery<Database['weight']>(query.sql, [...query.parameters]);
```

data is then used in a FlatList.

As mentioned earlier, I tried the same without Kysely, but that didn't make a difference.


**with latest versions:**
"@powersync/op-sqlite": "^0.7.11",
"@powersync/react-native": "^1.25.1",

after executing the update:

```
 INFO  Could not apply checkpoint due to local data. Will retry at completed upload or next checkpoint.
 DEBUG  Created write checkpoint: 3
 DEBUG  Updating target write checkpoint to 3
 DEBUG  Validated and applied checkpoint
```

data and FlatList **don't update.** But the updated value is stored, because when leaving and returning to the screen, I can see the newly stored value.
  
**with older versions:**
"@powersync/op-sqlite": "0.7.8",
"@powersync/react-native": "1.24.2",
  
after executing the update:

```
 INFO  Could not apply checkpoint due to local data. Will retry at completed upload or next checkpoint.
 DEBUG  Created write checkpoint: 6
 DEBUG  Updating target write checkpoint to 6
 DEBUG  Validated and applied checkpoint
```

data and FlatList are **immediately updated**.
  

This error `ERROR  [Error: Closed. Original cause [Error: Stream end encountered].]`  and the stack trace below seem to be caused by random disconnects of the websocket, and are not related.

**Comment by stevensJourney** [comment]
There were some previous issues where React hooks could miss updates, but those should all have been fixed if using the latest version.

As a test, could you check if `"@powersync/react-native": "1.24.3"` works on your end? That correlates to `@powersync/react@1.7.4`

Could you also log the state of `isFetching` and `isLoading` and `error` from the `useQuery` after the mutation?

As another check, could you also check in your lockfile if you might have multiple versions of `@powersync/common` present in the project - or share the current version which is present.

**Comment by sboo** [comment]
I added this to the code:

```
useEffect(() => {
    console.log('isLoading', isLoading);
  }, [isLoading]);

  useEffect(() => {
    console.log('isFetching', isFetching);
  }, [isFetching]);

  useEffect(() => {
    console.log('data updated');
  }, [data]);
```

after updating to 1.24.3, I get the same issue again:
update is not triggered, FlatList data doesn't update, and none of my hooks either.

Also I get the websocket timeout again.

There are indeed various versions of @powersync/common installed:

```
$ bun pm why @powersync/common
[1.19ms] ".env.local"
@powersync/common@1.37.0
  ├─ peer @powersync/attachments@2.4.0 (requires ^1.36.0)
  │  └─ my-app (requires ^2.4.0)
  └─ peer @powersync/kysely-driver@1.3.0 (requires ^1.36.0)
     └─ my-app (requires 1.3.0)

@powersync/common@1.38.0
  └─ @powersync/op-sqlite@0.7.8 (requires 1.38.0)
     └─ my-app(requires 0.7.8)

@powersync/common@1.40.0
  └─ peer @powersync/react@1.7.4 (requires ^1.38.1)
     └─ @powersync/react-native@1.24.3 (requires 1.7.4)
        └─ my-app(requires 1.24.3)

@powersync/common@1.38.1
  └─ @powersync/react-native@1.24.3 (requires 1.38.1)
     └─ my-app(requires 1.24.3)
```


downgrading again to 1.42.2:

my hooks are still not triggered, neither when I update from within the app or from another instance. data in the FlatList is updated though.

Fewer versions of @powersync/common installed:

```
$ bun pm why @powersync/common
[2.39ms] ".env.local"
@powersync/common@1.37.0
  ├─ peer @powersync/attachments@2.4.0 (requires ^1.36.0)
  │  └─ my-app (requires ^2.4.0)
  └─ peer @powersync/kysely-driver@1.3.0 (requires ^1.36.0)
     └─ my-app (requires 1.3.0)

@powersync/common@1.38.0
  ├─ @powersync/op-sqlite@0.7.8 (requires 1.38.0)
  │  └─ my-app (requires 0.7.8)
  └─ @powersync/react-native@1.24.2 (requires 1.38.0)
     └─ my-app (requires 1.24.2)

@powersync/common@1.40.0
  └─ peer @powersync/react@1.7.3 (requires ^1.38.0)
     └─ @powersync/react-native@1.24.2 (requires 1.7.3)
        └─ my-app (requires 1.24.2)

```

**Comment by sboo** [comment]
I cleaned up the duplicated libraries, but the issue with v 1.24.3 remains, update is not fired.

Here's the cleaned up selection:
```
$ bun pm why @powersync/common
[1.23ms] ".env.local"
@powersync/common@1.38.1
  ├─ @powersync/react-native@1.24.3 (requires 1.38.1)
  │  └─ ralph-pet-wellbeing (requires 1.24.3)
  ├─ peer @powersync/attachments@2.4.0 (requires ^1.36.0)
  │  └─ ralph-pet-wellbeing (requires ^2.4.0)
  ├─ peer @powersync/kysely-driver@1.3.0 (requires ^1.36.0)
  │  └─ ralph-pet-wellbeing (requires 1.3.0)
  └─ peer @powersync/react@1.7.4 (requires ^1.38.1)
     └─ @powersync/react-native@1.24.3 (requires 1.7.4)
        └─ ralph-pet-wellbeing (requires 1.24.3)

@powersync/common@1.38.0
  └─ @powersync/op-sqlite@0.7.8 (requires 1.38.0)
     └─ ralph-pet-wellbeing (requires 0.7.8)
```

When using v1.24.2, it's now all @powersync/common@1.38.0

**Comment by stevensJourney** [comment]
Thanks for the detailed information. We'll try and reproduce this locally in order to debug further.

**Comment by Chriztiaan** [comment]
Hey @sboo, I have tried to reproduce this on my side with no luck so far. Basically just extracting our `react-native-supabase-todolist` demo into a standalone project and using the latest versions of our dependencies. I tested older versions too, all on iOS 26.

Can you try the following set of versions?
```
"@op-engineering/op-sqlite": "14.0.2",
"@powersync/attachments": "2.4.0",
"@powersync/common": "1.40.0",
"@powersync/op-sqlite": "^0.7.11",
"@powersync/react": "1.8.1",
"@powersync/react-native": "1.25.1",
```

It might help to nuke your node_modules directory, potentially even your lock file just in case. It would be good to confirm that the lock file isn't referencing other versions.

**Comment by sboo** [comment]
I still get stuck in my project. I'll set up the Todo list and see what i need to do to break it, or where the differences are. I'll report back.

There might be some unforseen combination of packages or set up, because also updateSchema doesn't work flawlessly in my project.

**Comment by sboo** [comment]
I think I finally found the issue. I had missed this dev dependency from the instructions:

@babel/plugin-transform-async-generator-functions

This seems to have solved my problems, but didn't seem to have caused issues in the older packages.

**Comment by Chriztiaan** [comment]
Thank you for following up and sharing your findings @sboo, please feel welcome to reach out if you hit any other blockers.
